- name: install apache and php (CentOS)
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
- name: install apache and php (Ubuntu)
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
- name: copy default html file for site
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
- name: install unzip
  package:
    name: unzip
- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes