---

- hosts: web_servers
  become: true
  tasks:

    - name: start apache service (CentOS)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"